server:
  port: 8085
spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://localhost:3306/auth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 2461.Atay
    username: root
  jpa:
    hibernate:
      ddl-auto: update
