server:
  port: 8082
spring:
  application:
    name: payment
  datasource:
    url: jdbc:mysql://localhost:3306/payment?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 2461.Atay
    username: root
  jpa:
    hibernate:
      ddl-auto: update
